Hogsters
Cardano-NFTs/policyIDs pull request #109
Opened 2021-08-05 04:14 UTC by miguelhunter

Apologies for the double requests. Please disregard the first one and use the 'updated' one.  Thanks!

2021-08-05 10:41 UTC, itsmestale commented on Hogsters
> +        "7dc5a4ba313d62430ac0bc6c192b234d60089a76549e49b40b536e8a",
remove comma from this line

2021-08-05 10:41 UTC, itsmestale requested changes
remove comma from last policy id

2021-08-05 10:42 UTC, itsmestale commented
also please read the readme regarding twitter verification

2021-08-17 02:36 UTC, miguelhunter commented on Hogsters
> +        "7dc5a4ba313d62430ac0bc6c192b234d60089a76549e49b40b536e8a",
done!

2021-08-17 10:54 UTC, Dean00K approved these changes

2021-08-17 14:56 UTC, merged